### ISSUE TITLE
TypeError: Cannot convert undefined value to object on first launch

### ISSUE THREAD

**Issue by thespacemanatee** [marklawlor/tailwindcss-react-native#60]
Hello,

I hope I'm not doing something wrong as this is the 3rd issue we've run into setting up this library. When the app is first launched in the development environment (not sure about production), we are faced with this error

<img src="https://user-images.githubusercontent.com/6837599/170306353-dbff7acd-08fa-4192-a123-88c34cada5cc.png" width=400 />

The only way around this was to remove all `className`s and re-add them while the app is running, which is just not feasible if the app is any more complex than a hello world application. Followed the simplest version of the instructions on the documentation website.

### Environment
```
expo@45.0.4
tailwindcss-react-native@1.4.0
```

**Comment by marklawlor** [comment]
Hi @thespacemanatee, I created a new project following the [quick-start guide](https://tailwindcss-react-native.vercel.app/quick-start) but was unable to reproduce your issue.

Can you please create a new project following the quick-start guide and verify if the issue persists? If it does, can you please push the code to a public repo so I can help debug your issue.

**Comment by thespacemanatee** [comment]
Hi @marklawlor, I have created a repro at https://github.com/thespacemanatee/tailwind-issue-60 and added you as a collaborator. In this example, the error should appear on the first launch, and after clearing `className` in `App.tsx` and adding it back, the app should work as per normal until the next restart.

**Comment by marklawlor** [comment]
@thespacemanatee That repro fails to build for me and I do not have the capacity to debug its installation. In addition providing me while such a large project is only going to slow down the debugging process. I highly recommend modifying the MVP https://github.com/marklawlor/tailwind-issue-58 to demonstrate your issue.

I don't believe you need your entire application to demonstrate this issue. From the description you provided, the bug should be demonstrable within a single `App.tsx` file with no other dependencies?

If you cannot replicate the issue in https://github.com/marklawlor/tailwind-issue-58, thats good! You've isolated it to a dependency/component issue with your current project. You can then either isolate the issue by slowing adding your dependencies/screens until the bug is reproducible. Or, in your repo, start by deleting dependencies/screens until you can isolate the issue.

**Comment by thespacemanatee** [comment]
@marklawlor I have removed most of the useless files in the repro and can still reproduce it. I have added some instructions in the README.md for how to run the project. It definitely builds as I cloned it myself after uploading it. The app is running on Expo Bare workflow in case you were trying to build it for Expo Go. I will try to remove my other dependencies one by one but hopefully, we can investigate this in parallel so that we can find the root cause faster.

**Comment by thespacemanatee** [comment]
@marklawlor I have narrowed down the issue to my `metro.config.js`, deleting it solves this problem. Do you have any idea why it doesn't play well with this library? I am configuring it manually to support `expo-updates` and `react-native-svg-transformer`.

**Comment by marklawlor** [comment]
I'm not sure, most likely an issue with your custom babelTransformer. From a quick look at react-native-svg-transformer, your config does not match they're "with expo" instructions. It merges the transformer config instead of completely overriding it.

**Comment by thespacemanatee** [comment]
@marklawlor following facebook/react-native#25634, changing `inlineRequires: false` to `inlineRequires: true` solves this problem (still yet to understand its side-effects). Only happening after installing this library so may be something to consider. Regarding what you mentioned about my config, it looks correct to me since I'm using Bare workflow.

**Comment by marklawlor** [comment]
`inlineRequires: true` might be an issue due to how hot-reloading / style injection works. I'll investigate that a bit more

**Comment by marklawlor** [comment]
@thespacemanatee  Can you please test `v1.4.6-2`.

**Comment by marklawlor** [comment]
You will also need to reset your cache after installing that version.

**Comment by thespacemanatee** [comment]
@marklawlor happy to report that it works! Awesome🥇
