### ISSUE TITLE
I can't make it work with EXPO / EXPO GO

### ISSUE THREAD

**Issue by alexandreandriesse** [marklawlor/tailwindcss-react-native#61]
Hello, 

I'm super exited by this project, but I can't manage to make it work in my current expo project.
(I'm on the currently on the last version of expo)

I followed all installation steps, and I have no error/warning, it just don't work with Expo GO. 

Maybe it's not compatible ? Thx

**Comment by marklawlor** [comment]
Hi @alexandreandriesse, I use Expo Go everyday with this library - so it should be working for you 

Can you please answer a couple of questions

- When you followed the installation steps was this with a new or old project?
- If you create a new project with the quick-setup guide, does that work in expo?
- If you create a new Expo project with create-react-native-app but **don't use** this library, does that work for you?
- Have you tried the latest SDK?
- Can you describe "doesn't work" in a more detailed way (app crashes, blank screen, stuck on building, error overlay, etc)

Without more information I can't provide further help

**Comment by alexandreandriesse** [comment]
Hello Mark, 

Thx for your quick response. 

It's an old project.
All work without this library.
I'm working on SDK 44.
My "doesn't work" mean : i can use my app normaly (no crush, no blanc screen, no stuck, no error), but it is like the tailwind library is not installed. It don't apply tailwind inline className styles. 

Does the library support the expo go hot reload ? Should I use a special command line ? 

I will try to ugrade sdk 45.
I have unmeet dependency postcss, I tried to install it but didn't work.

**Comment by alexandreandriesse** [comment]
my tailwind.config.js : 
`module.exports = {
  content: ["./screens/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
};`

my babel.config.js : 
`module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["tailwindcss-react-native/babel", "react-native-reanimated/plugin"],
  };
};
`
 Should I install postcss manually ? Does the lib need a postcss.config.js ?

**Comment by marklawlor** [comment]
Can you please test in a new project - you need to isolate if it's just an issue with your old project or if this library isn't working at all on your system. Can you also please look at https://github.com/marklawlor/tailwindcss-react-native/issues/57 as you may be affected by it.

> I have unmeet dependency postcss, I tried to install it but didn't work.

This library installs PostCSS as a dependency, you don't need to install it yourself. Please carefully re-read that error message.

> Does the library support the expo go hot reload ? Should I use a special command line ?

Hot reload should work as expected. I would suggest creating a new project to confirm this.

> Should I install postcss manually?

No, unless your package manage explicitly requires it (eg due to a conflict). You should read the messages it produces during an install. 

> Does the lib need a postcss.config.js ?

Depends on what guide your are following for compilation. Since it looks like you are using Babel, no.

@alexandreandriesse I'm happy to answer these questions but without clear information on your issue I'm not going to be able to provide answers to the actual problem. Can you create a public repo where you can reproduce the issue? This will save us a lot of back and forth and allow me to provide you with a concise answer. I have an example repo here that you can use as a starter https://github.com/marklawlor/tailwind-issue-58 (just clone it, `npm install`, `npm start`)

**Comment by alexandreandriesse** [comment]
Hi, I made a new project (in TS), still without success, you can find it there => https://github.com/alexandreandriesse/tailwind-react-native-issue 

Here is the warning for unmet dependency : 
warning " > tailwindcss@3.0.24" has unmet peer dependency "postcss@^8.0.9".

**Comment by marklawlor** [comment]
That repo does not have this project setup at all?

Please follow the setup instructions https://tailwindcss-react-native.vercel.app/installation

When I follow these instructions on that repo it works as expected.

**Comment by alexandreandriesse** [comment]
Oups sorry I forgot to commit and push

**Comment by marklawlor** [comment]
That code is working correctly for me. I am testing in Android Emulator Pixel_5 with API_32 and physically on a Galaxy S10.

Can you provide more information about the environment you are using? 

- Are you on mac/windows? 
- Testing with iOS/Android?
- Do you have another computer to test with?
- You could also try testing with Expo Web https://tailwindcss-react-native.vercel.app/frameworks/expo#expo-web

You could also clone this repo and run its test suite on your local machine (`npm test`) to see if it reports any errors

**Comment by alexandreandriesse** [comment]
Of course  !

Computer OS: Windows 11
Testing Device : Android (Xiaomi 9T pro)
I have only one computer :/
No error with yarn test.
 
I'll try running it on an emulator.

**Comment by marklawlor** [comment]
I switched the CI environment to windows and there are some failing tests - they would also explain your issue. But this could be something else if the tests worked fine on your machine.

I'll have to setup a Windows development machine over the weekend to test it.

**Comment by marklawlor** [comment]
@alexandreandriesse Can you please test the latest version `v1.5.1`, it contains some fixes for Windows users.

**Comment by alexandreandriesse** [comment]
Hi Mark ! 

You are SUPER reactive. 
It seem to work perfectly now, thank you very much 😃 !!
I'm already in love with your library.
